version: '2'

volumes:
    webroot:
        driver: local

services:
    app:
        build:
            context: ../../
            dockerfile: docker/release/Dockerfile
        links:
            - db
        environment:
            DJANGO_SETTINGS_MODULE: todobackend.settings.release
            MYSQL_HOST: db
            MYSQL_USER: root
            MYSQL_PASSWORD: password
        command:
            - uwsgi
            - "--socket /var/www/todobackend/todobackend.sock"
            - "--chmod-socket=666"
            - "--module todobackend.wsgi"
            - "--master"
            - "--die-on-term"
        volumes:
            - webroot:/var/www/todobackend

    test:
        image: vlfedotov/todobackend-specs
        links:
            - nginx
        environment:
            URL: http://nginx:8000/todos
            JUNIT_REPORT_PATH: /reports/acceptance.xml
            JUNIT_REPORT_STACK: 1 
        command: --reporter mocha-jenkins-reporter

    db:
        image: mysql
        hostname: db
        expose:
            - "3306"
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: todobackend

    agent:
        image: vlfedotov/ansible
        links:
            - db
        environment:
            PROBE_HOST: "db"
            PROBE_PORT: "3306"
        command: ["probe.yml"]

    nginx:
        build: 
            context: .
            dockerfile: Dockerfile.nginx
        links:
            - app
        volumes:
            - webroot:/var/www/todobackend
        ports:
            - "58000:8000"
